server:
  port: 8083

spring:
  application:
    name: location-service
  jpa:
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: skydive_forecast_location
    database-change-log-table: skydive_forecast_location.DATABASECHANGELOG
    database-change-log-lock-table: skydive_forecast_location.DATABASECHANGELOGLOCK
  data:
    redis:
      host: redis
      port: 6379
      password: pass
      database: 0
      timeout: 2000ms
  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}

loki:
  url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}

springdoc:
  api-docs:
    path: /v3/api-docs/locations
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs/locations.yaml

jwt:
  secret: change-me-please-and-make-it-at-least-32-characters-long
