spring:
  datasource:
    url: jdbc:postgresql://postgres-analysis:5432/skydive_forecast_analysis_db
    username: skydive_forecast_analysis
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: skydive_forecast_analysis
    show-sql: true
  liquibase:
    enabled: false
    default-schema: skydive_forecast_analysis
  kafka:
    bootstrap-servers: kafka:9092
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:no-key}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: your-model-id
          temperature: 0.7

logging:
  level:
    root: INFO

jwt:
  secret: hK8nX2mP9qR5vT3wL7bE4jY6cA1dF8sZ

location:
  service:
    url: http://location-service:8083