spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: skydive_forecast_analysis
    show-sql: true
  liquibase:
    enabled: true
    default-schema: skydive_forecast_analysis
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: your-model-id
          temperature: 0.7

logging:
  level:
    root: INFO

jwt:
  secret: ${JWT_SECRET_KEY}
