spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: users
              uri: ${USER_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/users/**
            - id: analyses
              uri: ${ANALYSIS_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/v1/analyses/**
            - id: locations
              uri: ${LOCATION_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/v1/locations/**