server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: user-service
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    database-change-log-table: skydive-forecast.DATABASECHANGELOG
    database-change-log-lock-table: skydive-forecast.DATABASECHANGELOGLOCK
    contexts: default
  data:
    redis:
      host: redis
      port: 6379
      password: pass
      database: 0
      timeout: 2000ms
  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}

loki:
  url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}

springdoc:
  api-docs:
    path: /v3/api-docs/users
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs/users.yaml

jwt:
  expiration: 3600000         # 1 hour (ms)
  refresh-expiration: 604800000 # 7 days (ms)
  secret: change-me-please-and-make-it-at-least-32-characters-long
